name = "BBModels"
uuid = "adf32eb0-fe7e-47bb-93e4-fe96e72f6839"
authors = ["Abel Soares Siqueira <abel.s.siqueira@gmail.com> and contributors"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
SolverCore = "ff4d7338-4cf1-434d-91df-b86cb86fb843"
SolverParameters = "d076d87d-d1f9-4ea3-a44b-64b4cdd1e470"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
BenchmarkTools = "1"
LinearOperators = "2"
NLPModels = "0.19, 0.20"
SolverCore = "0.3"
julia = "1.6"

[extras]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
NLPModelsModifiers = "e01155f1-5c6f-4375-a9d8-616dd036575f"
OptimizationProblems = "5049e819-d29b-5fba-b941-0eee7e64c1c6"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SolverTools = "b5612192-2639-5dc1-abfe-fbedd65fab29"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ADNLPModels", "Krylov", "LinearAlgebra", "Logging", "NLPModelsModifiers", "OptimizationProblems", "Printf", "SolverTools", "Test"]
